Neo 기준으로 빌드 스크립트를 수정합니다
spoqa/spoqa-han-sans pull request #179
Opened 2021-03-18 05:48 UTC by KimWooHyun

2021-03-18 06:03 UTC, pbzweihander approved these changes

2021-03-18 09:08 UTC, Jhuni0123 requested changes

2021-03-18 09:08 UTC, Jhuni0123 commented on build_release
> +    fi
```suggestion
  if [[ "$2" = *Neo* ]]; then
    release_dirname="SpoqaHanSansNeo_$1";
  fi
```
인덴트는 요렇게 부탁드립니다 ㅎㅎ

2021-04-08 01:16 UTC, Jhuni0123 approved these changes

2021-04-08 04:30 UTC, merged